[project]
name = "katrfireport"
authors = [{name="Isaac Sihlangu", email='isihlangu@sarao.ac.za'},]
description = "This repository package an interactive bokeh-based RFI statistics report for MeerKAT observation"
requires-python = ">=3.8"
license = {file = "LICENSE"}
classifiers = [
    'Development Status :: 1 - Planning',
    'Intended Audience :: Science/Research',
    'Operating System :: POSIX :: Linux',
    'Programming Language :: Python :: 3.10',
]
dependencies = [
    "bokeh>=3.0.0",
    "importlib-resources",
    "katsdpservices",
    "katdal"
]
dynamic = ["version"]
[project.scripts]
"rfi_report" = "katrfireport.rfi_report_script:main"

[project.urls]
Homepage="https://github.com/https://github.com/ska-sa/katrfireport"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"katrfireport" = ["conf/*.csv"]

[build-system]
requires = [
        "setuptools>=45",
        "setuptools_scm[toml]>=6.0",
]

[tool.setuptools_scm]
